map $msie $cache_control {

        default "max-age=31536000, immutable";
        "1"     "max-age=31536000, public, no-transform,  immutable";

    }


server {
    listen       80 default_server;
    server_name  _;

    #access_log  /var/log/angie/host.access.log  main;
    set $root_path '/usr/share/angie/html';
    root   $root_path;
    
    set $msie default;

    rewrite ^/error /error/index.html permanent;
    rewrite ^/404  /error/index.html  last;
       
    location ~ /\. {
	
	deny all;	

    }
    
    location / {
	
	try_files $uri $uri/ =404;
    
    }


    location /images {

        root $root_path;
	add_header Cache-Control $cache_control;

    }

  
    location /assets/css {

        root $root_path;
        add_header Cache-Control $cache_control;

    }

    
    location /assets/js {

        root $root_path;
        add_header Cache-Control $cache_control;

    }

    
    location /assets/fonts {

        root $root_path;
        add_header Cache-Control $cache_control;

    }

    location /assets/sass {

        root $root_path;
        add_header Cache-Control $cache_control;

    }


    location ~* \.(?:ico|jpe?g|gif|png)$ {

  	set $msie "1";
	add_header Cache-Control $cache_control;
       
    }    

    error_page  404  /error/index.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /error/index.html;
    location = /error/index.html {
        root   $root_path;
    }

}

